### ISSUE TITLE
Unable to integrate this via cocoapods

### ISSUE THREAD

**Issue by mmdock** [rudderlabs/rudder-integration-branch-ios#2]
Trying to add branch to my rudderstack implementation, but there appears to be a number of errors occurring. 

<img width="939" alt="Screen Shot 2021-08-31 at 3 16 56 AM" src="https://user-images.githubusercontent.com/2423465/131485636-6d808f2a-9f89-40c1-bc36-a32254697ba1.png">

<img width="418" alt="Screen Shot 2021-08-31 at 3 14 39 AM" src="https://user-images.githubusercontent.com/2423465/131485421-1a301e16-1b48-419c-adc2-91f54218ac24.png">

**Comment by desusai7** [comment]
Hey @mmdock , Can you please try updating to version `1.0.0` of `Rudder-Branch` pod.

**Comment by desusai7** [comment]
@mmdock , please let us know if upgrading to `1.0.0` worked for you so that we could close the issue

**Comment by mmdock** [comment]
@desusai7  oh whoops, i didn't even notice - i was just going through this documentation here https://docs.rudderstack.com/destinations/attribution/branchio and thought that 0.1.3 was the updated version.

Looks like it's building now, thanks!

**Comment by pallabmaiti** [comment]
Thanks for the update @mmdock
